### PR TITLE
Import equipment tests from rsmp_validator

### PR DESCRIPTION
**Pull request by otterdahl**
Import GitHub Actions for equipment tests from rsmp_validator. Discussed in https://github.com/rsmp-nordic/rsmp_validator/issues/73

Triggering GitHub Actions across different repositories. See https://blog.marcnuri.com/triggering-github-actions-across-different-repositories

- [x] Import workflows from rsmp_validator
- [x] Move the ITC2 runner from rsmp_validator repo to the organization
- [x] Make sure the workflows perform git checkout for rsmp_validator instead
- [x] Workflow: Set up ACCESS_TOKEN
- [x] Workflow: Set up remote dispatch responder
- [x] Workflow: Set up remote dispatch action initiator in the rsmp_validator repo
- [x] Trigger the workflows from rsmp_validator
- [x] Make sure the equipment workflows runs when receiving the remote dispatch

### CODE REVIEW

**Comment by emiltin** [comment]
is there a default runner now in the rsmp_validator repo? we still need the doc build action

**Comment by otterdahl** [comment]
> is there a default runner now in the rsmp_validator repo? we still need the doc build action

The runners are available for the entire organization, not just a single repo. The doc build action should continue to work as before.

**Comment by emiltin** [comment]
> > is there a default runner now in the rsmp_validator repo? we still need the doc build action
> 
> The runners are available for the entire organization, not just a single repo. The doc build action should continue to work as before.

i see. how many jobs can run at the same time? it's unfortunate if the doc build action (which takes just 10-20s) must wait for a test equipment run to complete, which can take an hour

**Comment by otterdahl** [comment]
> i see. how many jobs can run at the same time? it's unfortunate if the doc build action (which takes just 10-20s) must wait for a test equipment run to complete, which can take an hour

One job per runner can run at the same time as far as I understand. I don't know if you can make them run in parallel.

What we could do is to try to change `runs-on` to include windows as well.

```
    runs-on: ubuntu-latest
```

**Comment by emiltin** [comment]
> One job per runner can run at the same time as far as I understand. I don't know if you can make them run in parallel.

each of the laptops connected to a piece of equipment is a runner?

**Comment by otterdahl** [comment]
> each of the laptops connected to a piece of equipment is a runner?

yes

**Pull request merged**
